from __future__ import annotations

from importlib import import_module
from typing import Any

from ..params import (
    BertopicKMeansParams,
    BleiLdaParams,
    CtmParams,
    EtmParams,
    GaussianKMeansParams,
    GaussianLdaParams,
    GaussianMixtureParams,
    MovMFParams,
    MvTMParams,
    SenCluParams,
    SentenceGaussianLdaParams,
    SentLdaParams,
    SphericalKMeansParams,
    parse_bertopic_kmeans_params,
    parse_bleilda_params,
    parse_ctm_params,
    parse_etm_params,
    parse_gaussian_kmeans_params,
    parse_gaussian_mixture_params,
    parse_gaussianlda_params,
    parse_movmf_params,
    parse_mvtm_params,
    parse_senclu_params,
    parse_sentence_gaussianlda_params,
    parse_sentlda_params,
    parse_spherical_kmeans_params,
)

_EXPORT_MODULES = {
    "BertopicKMeansInferResult": "bertopic_kmeans",
    "BertopicKMeansTrainResult": "bertopic_kmeans",
    "infer_bertopic_kmeans": "bertopic_kmeans",
    "persist_bertopic_kmeans_run": "bertopic_kmeans",
    "train_bertopic_kmeans": "bertopic_kmeans",
    "BleiLdaInferResult": "bleilda",
    "BleiLdaTrainResult": "bleilda",
    "infer_bleilda": "bleilda",
    "persist_bleilda_run": "bleilda",
    "train_bleilda": "bleilda",
    "CtmInferResult": "ctm",
    "CtmTrainResult": "ctm",
    "infer_ctm": "ctm",
    "persist_ctm_run": "ctm",
    "train_ctm": "ctm",
    "EtmInferResult": "etm",
    "EtmModel": "etm",
    "EtmTrainResult": "etm",
    "infer_etm": "etm",
    "persist_etm_run": "etm",
    "train_etm": "etm",
    "GaussianLdaInferResult": "gaussianlda",
    "GaussianLdaTrainResult": "gaussianlda",
    "PreparedWordVectorCorpus": "gaussianlda",
    "infer_gaussianlda": "gaussianlda",
    "persist_gaussianlda_run": "gaussianlda",
    "prepare_word_vector_corpus": "gaussianlda",
    "train_gaussianlda": "gaussianlda",
    "MvTMInferResult": "mvtm",
    "MvTMTrainResult": "mvtm",
    "WordVectorEncoder": "mvtm",
    "infer_mvtm": "mvtm",
    "persist_mvtm_run": "mvtm",
    "train_mvtm": "mvtm",
    "SenCluInferResult": "senclu",
    "SenCluTrainResult": "senclu",
    "infer_senclu": "senclu",
    "persist_senclu_run": "senclu",
    "train_senclu": "senclu",
    "SentenceEmbeddingClusteringInferResult": "sentence_embedding_clustering",
    "SentenceEmbeddingClusteringModelState": "sentence_embedding_clustering",
    "SentenceEmbeddingClusteringTrainResult": "sentence_embedding_clustering",
    "infer_gaussian_kmeans": "sentence_embedding_clustering",
    "infer_gaussian_mixture": "sentence_embedding_clustering",
    "infer_movmf": "sentence_embedding_clustering",
    "infer_spherical_kmeans": "sentence_embedding_clustering",
    "persist_gaussian_kmeans_run": "sentence_embedding_clustering",
    "persist_gaussian_mixture_run": "sentence_embedding_clustering",
    "persist_movmf_run": "sentence_embedding_clustering",
    "persist_spherical_kmeans_run": "sentence_embedding_clustering",
    "train_gaussian_kmeans": "sentence_embedding_clustering",
    "train_gaussian_mixture": "sentence_embedding_clustering",
    "train_movmf": "sentence_embedding_clustering",
    "train_spherical_kmeans": "sentence_embedding_clustering",
    "SentenceGaussianLdaInferResult": "sentence_gaussianlda",
    "SentenceGaussianLdaTrainResult": "sentence_gaussianlda",
    "infer_sentence_gaussianlda": "sentence_gaussianlda",
    "persist_sentence_gaussianlda_run": "sentence_gaussianlda",
    "train_sentence_gaussianlda": "sentence_gaussianlda",
    "SentLdaInferResult": "sentlda",
    "SentLdaTrainResult": "sentlda",
    "infer_sentlda": "sentlda",
    "persist_sentlda_run": "sentlda",
    "train_sentlda": "sentlda",
}

__all__ = [
    "BertopicKMeansInferResult",
    "BertopicKMeansParams",
    "BertopicKMeansTrainResult",
    "BleiLdaInferResult",
    "BleiLdaParams",
    "BleiLdaTrainResult",
    "CtmInferResult",
    "CtmParams",
    "CtmTrainResult",
    "EtmInferResult",
    "EtmModel",
    "EtmParams",
    "EtmTrainResult",
    "GaussianKMeansParams",
    "GaussianLdaInferResult",
    "GaussianLdaParams",
    "GaussianLdaTrainResult",
    "GaussianMixtureParams",
    "MovMFParams",
    "MvTMInferResult",
    "MvTMParams",
    "MvTMTrainResult",
    "PreparedWordVectorCorpus",
    "SenCluInferResult",
    "SenCluParams",
    "SenCluTrainResult",
    "SentenceEmbeddingClusteringInferResult",
    "SentenceEmbeddingClusteringModelState",
    "SentenceEmbeddingClusteringTrainResult",
    "SentenceGaussianLdaInferResult",
    "SentenceGaussianLdaParams",
    "SentenceGaussianLdaTrainResult",
    "SentLdaInferResult",
    "SentLdaParams",
    "SentLdaTrainResult",
    "SphericalKMeansParams",
    "WordVectorEncoder",
    "infer_bertopic_kmeans",
    "infer_bleilda",
    "infer_ctm",
    "infer_etm",
    "infer_gaussian_kmeans",
    "infer_gaussian_mixture",
    "infer_gaussianlda",
    "infer_movmf",
    "infer_mvtm",
    "infer_senclu",
    "infer_sentence_gaussianlda",
    "infer_sentlda",
    "infer_spherical_kmeans",
    "parse_bertopic_kmeans_params",
    "parse_bleilda_params",
    "parse_ctm_params",
    "parse_etm_params",
    "parse_gaussian_kmeans_params",
    "parse_gaussian_mixture_params",
    "parse_gaussianlda_params",
    "parse_movmf_params",
    "parse_mvtm_params",
    "parse_senclu_params",
    "parse_sentence_gaussianlda_params",
    "parse_sentlda_params",
    "parse_spherical_kmeans_params",
    "persist_bertopic_kmeans_run",
    "persist_bleilda_run",
    "persist_ctm_run",
    "persist_etm_run",
    "persist_gaussian_kmeans_run",
    "persist_gaussian_mixture_run",
    "persist_gaussianlda_run",
    "persist_movmf_run",
    "persist_mvtm_run",
    "persist_senclu_run",
    "persist_sentence_gaussianlda_run",
    "persist_sentlda_run",
    "persist_spherical_kmeans_run",
    "prepare_word_vector_corpus",
    "train_bertopic_kmeans",
    "train_bleilda",
    "train_ctm",
    "train_etm",
    "train_gaussian_kmeans",
    "train_gaussian_mixture",
    "train_gaussianlda",
    "train_movmf",
    "train_mvtm",
    "train_senclu",
    "train_sentence_gaussianlda",
    "train_sentlda",
    "train_spherical_kmeans",
]


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f"{__name__}.{module_name}")
    value = getattr(module, name)
    globals()[name] = value
    return value
